---
- name: ansible for aws
  hosts: localhost
  gather_facts: False
  tasks:
    - name: create key-pair
      ec2_key:
        name: sample
        region: us-east-1
      register: keyout
      notify:
        - save key-pair
    - name: create instance
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        image_id: ami-0261755bbcb8c4a84
        wait: yes
        region: us-east-1
        network:
          assign_public_ip: True
          security_group: web01-tween-dev
        exact_count: 1
        tags:
          Name: db99
      
  handlers:
    - name: save key-pair
      copy:
        content: "{{keyout.key.private_key}}"
        dest: ./sample.pem
